apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    run: uengine-process
  name: uengine-process
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: uengine-process
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: uengine-process
    spec:
      containers:
      - image: gcr.io/my-project-1531888882785/uengine-process:v2
        imagePullPolicy: IfNotPresent
        name: uengine-process
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
