server:
  port: 8080

endpoints:
  routes:
    sensitive: false

management:
  security:
    enabled: false

security:
  basic:
    enabled: false

zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  addProxyHeaders: true

  # Decides to check the token.
  iam-authentication: true

  # Key to determine if the token's signature is correct.
  # It must be the same key that IAM used to issue the token.
  # Copy and paste from your IAM's iam.jwt.key
  iam-jwt-key: my-jwt-encrypt-key-my-jwt-encrypt-key

  routes:

    definition:
      path: /definition/**
      url: http://uengine-definition:9093
      stripPrefix: false
    create-app:
      path: /create-app/**
      url: http://uengine-definition:9093
      stripPrefix: false
    version:
      path: /version/**
      url: http://uengine-definition:9093
      stripPrefix: false
    instance:
      path: /instance/**
      url: http://uengine-process:9094
      stripPrefix: false
    instance-entity:
      path: /instances/**
      url: http://uengine-process:9094
      stripPrefix: false
    instance-service:
      path: /service/**
      url: http://uengine-process:9094
      stripPrefix: false
    instance-services:
      path: /services/**
      url: http://uengine-process:9094
      stripPrefix: false
    worklist-entity:
      path: /worklist/**
      url: http://uengine-process:9094
      stripPrefix: false
    instance-workitem:
      path: /work-item/**
      url: http://uengine-process:9094
      stripPrefix: false
    metadata:
      path: /classdefinition/**
      url: http://uengine-process:9094
      stripPrefix: false


#### important for BPM introspection  ####

    bpm:
      path: /bpm/**
      url: http://uengine-process:9094
      stripPrefix: true

#### proxies for reverse engineering and java code generation ###

    gitlab:
      url: http://gitlab.pas-mini.io/api/v4/
      stripPrefix: true
      addHeader:
        PRIVATE-TOKEN: 2A_LokKTbnywjw8shHy-



###########################################

ribbon:
  # Max number of retries on the same server (excluding the first try)
  MaxAutoRetries: 1

  # Max number of next servers to retry (excluding the first server)
  MaxAutoRetriesNextServer: 1

  # Whether all operations can be retried for this client
  OkToRetryOnAllOperations: true

  # Interval to refresh the server list from the source
  ServerListRefreshInterval: 2000

  # Connect timeout used by Apache HttpClient
  ConnectTimeout: 3000

  # Read timeout used by Apache HttpClient
  ReadTimeout: 3000

  # Initial list of servers, can be changed via Archaius dynamic property at runtime
  #listOfServers: www.microsoft.com:80,www.yahoo.com:80,www.google.com:80

