server:
  port: 9093

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: uengine-kafka:9092
          zkNodes: uengine-zookeeper:2181
      bindings:
        bpm-topic:
          destination: bpm.topic
          contentType: application/json
