server:
  port: 9093

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
          zkNodes: my-kafka-zookeeper:2181
      bindings:
        bpm-topic:
          destination: bpm.topic
          contentType: application/json
