apiVersion: v1
kind: Service
metadata:
  labels:
    run: uengine-definition
  name: uengine-definition
spec:
  ports:
  - port: 9093
    protocol: TCP
  selector:
    run: uengine-definition
  type: ClusterIP
