apiVersion: v1
kind: Service
metadata:
  labels:
    run: uengine-definition
  name: uengine-definition
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32464
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    run: uengine-definition
  type: LoadBalancer
