apiVersion: v1
kind: Service
metadata:
  labels:
    run: uengine-definition
  name: uengine-definition
spec:
  ports:
  - port: 9093
    targetPort: http
    protocol: TCP
    name: http
  selector:
    run: uengine-definition
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: uengine-definition
  name: uengine-definition
spec:
  ports:
  - port: 9093
    targetPort: http
    protocol: TCP
    name: http
  selector:
    run: uengine-definition
  type: ClusterIP
