spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: uengine-kafka:9092  # ${vcap.services.kakfa.host_port} and inject value from env variable
          zkNodes: uengine-zookeeper:2181
      bindings:
        bpm-topic:
          destination: bpm.topic
          contentType: application/json

eureka:
  client:
    enabled: false

server:
  port: 9094
  servletPath: /
#  ssl:
#    key-store: src/test/resources/keystore.p12
#    key-store-password: mypassword
#    keyStoreType: PKCS12
#    keyAlias: uengine

