spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
      bindings:
        bpm-topic:
          destination: bpm.topic
          contentType: application/json


server:
  port: 9094
  servletPath: /
#  ssl:
#    key-store: src/test/resources/keystore.p12
#    key-store-password: mypassword
#    keyStoreType: PKCS12
#    keyAlias: uengine

