apiVersion: v1
kind: Service
metadata:
  labels:
    run: uengine-definition
  name: uengine-definition
spec:
  ports:
  - port: 9093
    targetPort: 9093
    protocol: TCP
    name: http
  selector:
    run: uengine-definition
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: uengine-process
  name: uengine-process
spec:
  ports:
  - port: 9094
    targetPort: 9094
    protocol: TCP
    name: http
  selector:
    run: uengine-process
  type: ClusterIP

#---
#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    run: uengine-proxy
#  name: uengine-proxy
#spec:
#  ports:
#  - port: 8080
#    targetPort: 8080
#    protocol: TCP
#    name: http
#  selector:
#    run: uengine-proxy
#  type: LoadBalancer
#  {{- if $.Values.backend }}
#  loadBalancerIP: {{ .Values.backend.ip }}
#  {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: uengine-front
  name: uengine-front
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    run: uengine-front
  type: LoadBalancer
  {{- if $.Values.frontend }}
  loadBalancerIP: {{ .Values.frontend.ip }}
  {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: semantic-entity
  name: semantic-entity
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    run: semantic-entity
  type: ClusterIP
